#!/bin/sh

# Source function library
. /etc/rc.d/init.d/functions

# Get service config
[ -f /etc/sysconfig/hdparm ] && . /etc/sysconfig/hdparm

DRIVES="`awk '!($NF ~ /md|name/) { print $NF }' /proc/partitions`"
for drive in $DRIVES; do
	eval PARAMS=\${HDPARM_${drive}}
	if [ -n "${PARAMS}" ] ; then
		show "Setting parameters for drive %s" "$drive"
		busy
		/sbin/hdparm ${PARAMS} /dev/$drive
		deltext
		ok
	fi
done  
exit 0
